<a href="https://colab.research.google.com/github/saurabhsingh1411/Deep_Learning_Projects/blob/main/NLP/TOP%20PROJECTS/twitter%20sentiment%20analysis/twitter_Sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')



In [4]:
train.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [5]:
test.head()

id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

In [6]:
test['label']='test'

test.head()

id                                              tweet label
0  31963  #studiolife #aislife #requires #passion #dedic...  test
1  31964   @user #white #supremacists want everyone to s...  test
2  31965  safe ways to heal your #acne!!    #altwaystohe...  test
3  31966  is the hp and the cursed child book up for res...  test
4  31967    3rd #bihday to my amazing, hilarious #nephew...  test

In [13]:
test=test[['id','label','tweet']]

test.head()

id label                                              tweet
0  31963  test  #studiolife #aislife #requires #passion #dedic...
1  31964  test   @user #white #supremacists want everyone to s...
2  31965  test  safe ways to heal your #acne!!    #altwaystohe...
3  31966  test  is the hp and the cursed child book up for res...
4  31967  test    3rd #bihday to my amazing, hilarious #nephew...

In [30]:
data=pd.concat([train,test],axis=0,ignore_index=True,)

data.head()

id label                                              tweet
0   1     0   @user when a father is dysfunctional and is s...
1   2     0  @user @user thanks for #lyft credit i can't us...
2   3     0                                bihday your majesty
3   4     0  #model   i love u take with u all the time in ...
4   5     0             factsguide: society now    #motivation

In [32]:
print(train.shape)
print(test.shape)
print(data.shape)

(31962, 3)
(17197, 3)
(49159, 3)


In [33]:
print(type(train))
print(type(test))
print(type(data))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [34]:
print(data.shape[0])
print(train.shape[0])
print(test.shape[0])

49159
31962
17197


In [35]:
data['tweet'][0]

' @user when a father is dysfunctional and is so selfish he drags his kids into his dysfunction.   #run'

In [36]:
#cleaning the dataset
import re
def process_tweet(tweet):
    return " ".join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])", "",tweet.lower()).split())

In [37]:
processed_tweet=[]
for item in range(data.shape[0]):
  processed_tweet.append(process_tweet(data['tweet'][item]))

In [38]:
data['processed_tweet']=processed_tweet

data.head()

id  ...                                    processed_tweet
0   1  ...  when a father is dysfunctional and is so selfi...
1   2  ...  thanks for lyft credit i cant use cause they d...
2   3  ...                                bihday your majesty
3   4  ...      model i love u take with u all the time in ur
4   5  ...                  factsguide society now motivation

[5 rows x 4 columns]

Preprocessing the text

In [44]:
train_data=data[data['label']!='test']

print(train_data.shape)

(31962, 4)


In [45]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

max_feature=2000
tokenizer=Tokenizer(num_words=max_feature, split=' ')
tokenizer.fit_on_texts(train_data['processed_tweet'].values)
X=tokenizer.texts_to_sequences(train_data['processed_tweet'].values)
X=pad_sequences(X)

In [46]:
y=pd.get_dummies(data=train_data['label']).values

print(X.shape)
print(y.shape)

(31962, 32)
(31962, 2)


In [48]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(25569, 32) (25569, 2)
(6393, 32) (6393, 2)


In [49]:
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(n_estimators=300)

model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [50]:
y_pred=np.argmax(model.predict(X_test),axis=-1)

y_test=np.argmax(y_test,axis=-1)

In [51]:
print(y_pred)
print(y_test)

[0 0 0 ... 0 0 1]
[0 0 0 ... 0 0 1]


In [52]:
from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      5937
           1       0.98      0.27      0.43       456

    accuracy                           0.95      6393
   macro avg       0.96      0.64      0.70      6393
weighted avg       0.95      0.95      0.93      6393

[[5934    3]
 [ 331  125]]


Deep Learning Tools 

In [53]:
from keras.models import Sequential
from keras.layers import Embedding,LSTM,Dense,Dropout

embed_dim=128
lstm_out=196

model=Sequential()
model.add(Embedding(max_feature,embed_dim,input_length=X.shape[1]))
model.add(Dropout(0.4))
model.add(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(2,activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())



Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 32, 128)           256000    
_________________________________________________________________
dropout (Dropout)            (None, 32, 128)           0         
_________________________________________________________________
lstm (LSTM)                  (None, 196)               254800    
_________________________________________________________________
dense (Dense)                (None, 2)                 394       
Total params: 511,194
Trainable params: 511,194
Non-trainable params: 0
_________________________________________________________________
None


In [57]:
max_fatures = 2000
tokenizer = Tokenizer(num_words=max_fatures, split=' ')
tokenizer.fit_on_texts(train_data['processed_tweet'].values)
X = tokenizer.texts_to_sequences(train_data['processed_tweet'].values)
X = pad_sequences(X)



Y = pd.get_dummies(train_data['label']).values
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(25569, 32) (25569, 2)
(6393, 32) (6393, 2)


In [ ]:

batch_size = 32
model.fit(X_train, Y_train, epochs = 10, batch_size=batch_size,validation_data=(X_test ,Y_test))

Epoch 1/10
800/800 [==============================] - 153s 191ms/step - loss: 0.0964 - accuracy: 0.9647 - val_loss: 0.1362 - val_accuracy: 0.9517
Epoch 2/10
800/800 [==============================] - 154s 192ms/step - loss: 0.0841 - accuracy: 0.9680 - val_loss: 0.1464 - val_accuracy: 0.9537
Epoch 3/10
800/800 [==============================] - 154s 192ms/step - loss: 0.0743 - accuracy: 0.9718 - val_loss: 0.1404 - val_accuracy: 0.9521
Epoch 4/10
800/800 [==============================] - 155s 194ms/step - loss: 0.0655 - accuracy: 0.9745 - val_loss: 0.1592 - val_accuracy: 0.9490
Epoch 5/10
800/800 [==============================] - 155s 193ms/step - loss: 0.0584 - accuracy: 0.9785 - val_loss: 0.1788 - val_accuracy: 0.9545
Epoch 6/10
800/800 [==============================] - 155s 193ms/step - loss: 0.0535 - accuracy: 0.9805 - val_loss: 0.1880 - val_accuracy: 0.9514
Epoch 7/10
800/800 [==============================] - 154s 193ms/step - loss: 0.0448 - accuracy: 0.9840 - val_loss: 0.1974 -

In [ ]:
test_data=data[data['label']=='test']

max_fatures = 2000
tokenizer = Tokenizer(num_words=max_fatures, split=' ')
tokenizer.fit_on_texts(test_data['processed_tweet'].values)
X = tokenizer.texts_to_sequences(testdata['processed_tweet'].values)
X = pad_sequences(X)

y_pred=np.argmax(model.predict(X),axis=-1)


In [ ]:
test_data['prediction_label']=y_pred

test_data.head()