<a href="https://colab.research.google.com/github/saurabhsingh1411/Deep_Learning_Projects/blob/main/NLP/TOP%20PROJECTS/Email%20Spam%20Detections/Spam_Email_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
data=pd.read_csv('emails.csv')

data.head(5)

text  ... Unnamed: 109
0  Subject: naturally irresistible your corporate...  ...          NaN
1  Subject: the stock trading gunslinger  fanny i...  ...          NaN
2  Subject: unbelievable new homes made easy  im ...  ...          NaN
3  Subject: 4 color printing special  request add...  ...          NaN
4  Subject: do not have money , get software cds ...  ...          NaN

[5 rows x 110 columns]

In [3]:
data=data[['text','spam']]

data.head()

text spam
0  Subject: naturally irresistible your corporate...    1
1  Subject: the stock trading gunslinger  fanny i...    1
2  Subject: unbelievable new homes made easy  im ...    1
3  Subject: 4 color printing special  request add...    1
4  Subject: do not have money , get software cds ...    1

In [4]:
print(data.shape)
print(type(data))

(5730, 2)
<class 'pandas.core.frame.DataFrame'>


In [5]:
data.isnull().sum()

text    0
spam    2
dtype: int64

In [6]:
data['spam'].value_counts()

0                                                                                               4359
1                                                                                               1367
 mr suresh prabhu                                                                                  1
 its termination would not  have such a phenomenal impact on the power situation .  however        1
Name: spam, dtype: int64

In [10]:
# data=data.dropna()
# #data['spam']=data['spam'].replace(np.nan,0)
# data.isnull().sum()

text    0
spam    0
dtype: int64

In [7]:
data['spam'].value_counts()

0                                                                                               4359
1                                                                                               1367
 mr suresh prabhu                                                                                  1
 its termination would not  have such a phenomenal impact on the power situation .  however        1
Name: spam, dtype: int64

In [8]:
data[data['spam']==' mr suresh prabhu ']=np.nan
data['spam'].value_counts()

0                                                                                               4359
1                                                                                               1367
 its termination would not  have such a phenomenal impact on the power situation .  however        1
Name: spam, dtype: int64

In [9]:
data[data['spam']==' its termination would not  have such a phenomenal impact on the power situation .  however ']=np.nan
data['spam'].value_counts()

0    4359
1    1367
Name: spam, dtype: int64

In [10]:
data.isnull().sum()

text    2
spam    4
dtype: int64

In [10]:
# index=data.index
# required_index=index[data['spam']==' mr suresh prabhu '].tolist()

# required_index

In [11]:
data['text'][0]

"Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  ma

In [12]:
#cleaning the dataset
import re
def process_text(text):
    return " ".join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])", "",text.lower()).split())

In [13]:
type(data['text'][0])

str

In [14]:
data.shape[0]

5730

In [15]:
process_text(data['text'][5729])

'subject news aurora 5 2 update aurora version 5 2 the fastest model just got faster epis announces the release of aurora version 5 2 aurora the electric market price forecasting tool is already legendary for power and speed we ve combined a powerful chronological dispatch model with the capability to simulate the market from 1 day to 25 years add to that a risk analysis section powered by user selectable monte carlo or latin hypercube modeling enough portfolio analysis power to please the toughest critic inputs and outputs from standard excel access tables and you ve got one of most powerful tools in the market just a few months ago we expanded our emissions modeling capabilities added our quarterly database update increased the speed of the entire model and made but that wasn t enough we ve done it again some of the operations that we ve included two new reporting enhancements the first is marginal reporting for fuels resources and groups of resources the second is the ability to dis

In [16]:
processed_text=[]
for item in range(data.shape[0]):
  processed_text.append(process_text(str(data['text'][item])))

In [17]:
data['processed_text']=processed_text

data.head()

text  ...                                     processed_text
0  Subject: naturally irresistible your corporate...  ...  subject naturally irresistible your corporate ...
1  Subject: the stock trading gunslinger  fanny i...  ...  subject the stock trading gunslinger fanny is ...
2  Subject: unbelievable new homes made easy  im ...  ...  subject unbelievable new homes made easy im wa...
3  Subject: 4 color printing special  request add...  ...  subject 4 color printing special request addit...
4  Subject: do not have money , get software cds ...  ...  subject do not have money get software cds fro...

[5 rows x 3 columns]

In [19]:
data.isnull().sum()

text              2
spam              4
processed_text    0
dtype: int64

In [20]:
data=data.dropna()

data.isnull().sum()

text              0
spam              0
processed_text    0
dtype: int64

In [21]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

max_feature=2000
tokenizer=Tokenizer(num_words=max_feature,split=' ')
tokenizer.fit_on_texts(data['processed_text'].values)
X=tokenizer.texts_to_sequences(data['processed_text'].values)

X=pad_sequences(X)

In [22]:
data['spam'].value_counts()

0    4359
1    1367
Name: spam, dtype: int64

In [24]:
y=pd.get_dummies(data['spam']).values

print(X.shape)
print(y.shape)

(5726, 4458)
(5726, 2)


In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(4580, 4458) (4580, 2)
(1146, 4458) (1146, 2)


In [26]:
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(n_estimators=300)

model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [27]:
y_pred=np.argmax(model.predict(X_test),axis=-1)

y_test=np.argmax(y_test,axis=-1)

In [28]:

print(y_pred)
print(y_test)

[0 0 0 ... 1 0 0]
[0 0 0 ... 1 0 0]


In [29]:
from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.98      0.90       856
           1       0.89      0.37      0.52       290

    accuracy                           0.83      1146
   macro avg       0.86      0.68      0.71      1146
weighted avg       0.84      0.83      0.80      1146

[[843  13]
 [183 107]]



Deep Learning Tools

In [30]:
from keras.models import Sequential
from keras.layers import Embedding,LSTM,Dense,Dropout

embed_dim=128
lstm_out=196

model=Sequential()
model.add(Embedding(max_feature,embed_dim,input_length=X.shape[1]))
model.add(Dropout(0.4))
model.add(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(2,activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4458, 128)         256000    
_________________________________________________________________
dropout (Dropout)            (None, 4458, 128)         0         
_________________________________________________________________
lstm (LSTM)                  (None, 196)               254800    
_________________________________________________________________
dense (Dense)                (None, 2)                 394       
Total params: 511,194
Trainable params: 511,194
Non-trainable params: 0
_________________________________________________________________
None


In [34]:

max_fatures = 2000
tokenizer = Tokenizer(num_words=max_fatures, split=' ')
tokenizer.fit_on_texts(data['processed_text'].values)
X = tokenizer.texts_to_sequences(data['processed_text'].values)
X = pad_sequences(X)



Y = pd.get_dummies(data['spam']).values
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(4580, 4458) (4580, 2)
(1146, 4458) (1146, 2)


In [ ]:
#batch_size = 32
model.fit(X_train, Y_train, epochs = 5,validation_data=(X_test ,Y_test))

 13/144 [=>............................] - ETA: 1:00:09 - loss: 0.5599 - accuracy: 0.7548

In [ ]:
Thanks 