<a href="https://colab.research.google.com/github/saurabhsingh1411/Deep_Learning_Projects/blob/main/Time%20Series/Bitcoin%20Price%20Prediction/bitcoin_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('features.csv')
labels=pd.read_csv('labels.csv')

data.tail()

feature_timestamp  f0  f1  f2  f3  f4  f5
97352  2020-12-31 23:35:00+00:00   1   0   0   0   0   0
97353  2020-12-31 23:40:00+00:00   1   0   0   0   0   0
97354  2020-12-31 23:45:00+00:00   1   0   0   0   0   0
97355  2020-12-31 23:50:00+00:00   1   0   0   0   0   0
97356  2020-12-31 23:55:00+00:00   1   0   0   0   0   0

In [3]:
train=labels
train.head()

timestamp  label    weight    close
0  2020-01-01 00:10:00+00:00   -1.0  0.320526  7158.23
1  2020-01-01 00:15:00+00:00   -1.0  0.055105  7155.03
2  2020-01-01 00:20:00+00:00    1.0  0.363105  7154.48
3  2020-01-01 00:25:00+00:00    1.0  0.602664  7157.00
4  2020-01-01 00:30:00+00:00    1.0  0.569698  7159.21

In [8]:
train=labels

In [9]:
train.head()

close
0  7158.23
1  7155.03
2  7154.48
3  7157.00
4  7159.21

In [10]:
train.isnull().sum()

close    0
dtype: int64

In [11]:
train.shape

(105142, 1)

In [12]:
#variable for predicting n days into the future 
prediction_days=30 
train['prediction']=train['close'].shift(-prediction_days)

train.head(35)

close  prediction
0   7158.23     7211.00
1   7155.03     7210.60
2   7154.48     7217.00
3   7157.00     7217.00
4   7159.21     7212.74
5   7157.30     7200.02
6   7155.72     7200.01
7   7155.20     7207.51
8   7150.95     7208.48
9   7150.35     7207.79
10  7157.01     7209.99
11  7161.29     7202.73
12  7167.34     7193.41
13  7168.20     7199.19
14  7171.01     7200.00
15  7186.60     7196.98
16  7194.42     7199.55
17  7196.26     7198.19
18  7191.28     7190.08
19  7186.01     7192.53
20  7186.46     7192.53
21  7194.52     7196.00
22  7197.77     7198.06
23  7197.74     7198.00
24  7192.79     7197.97
25  7199.99     7199.00
26  7204.96     7190.01
27  7207.58     7186.41
28  7212.09     7195.51
29  7209.48     7198.12
30  7211.00     7199.00
31  7210.60     7196.01
32  7217.00     7196.01
33  7217.00     7194.99
34  7212.74     7194.84

In [13]:
train.tail(10)

close  prediction
105132  29124.50         NaN
105133  29142.72         NaN
105134  29070.41         NaN
105135  29054.03         NaN
105136  29022.68         NaN
105137  29040.81         NaN
105138  28880.65         NaN
105139  29020.24         NaN
105140  29040.46         NaN
105141  28990.08         NaN

In [14]:
#Creating the independent dataset(X)

X=np.array(train.drop(['prediction'],axis=1))

X=X[:len(train)-prediction_days]

print(X)

[[ 7158.23]
 [ 7155.03]
 [ 7154.48]
 ...
 [29191.54]
 [29129.63]
 [29149.68]]


In [15]:
y=np.array(train['prediction'])

#get the all of y except the last n rows 

y=y[:-prediction_days]

In [16]:
print(y)

[ 7211.    7210.6   7217.   ... 29020.24 29040.46 28990.08]


In [17]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [18]:
# Set prediction_days_array equal to the last 30 rows of the original data set from the price column

prediction_days_array=np.array(train.drop(['prediction'],axis=1))[-prediction_days:]

print(prediction_days_array)

[[29199.99]
 [29068.21]
 [29076.05]
 [29046.01]
 [29051.34]
 [29006.05]
 [29015.96]
 [29030.  ]
 [29098.05]
 [29100.  ]
 [29133.15]
 [29107.74]
 [29141.43]
 [29159.81]
 [29168.99]
 [29148.19]
 [29163.15]
 [29157.65]
 [29099.83]
 [29096.01]
 [29124.5 ]
 [29142.72]
 [29070.41]
 [29054.03]
 [29022.68]
 [29040.81]
 [28880.65]
 [29020.24]
 [29040.46]
 [28990.08]]


Preparing the model and validating the model

In [ ]:
from sklearn.svm import SVR 

#Create and train support vector machine 

svr_rbf=SVR(kernel='rbf')  #Create the Model 
svr_rbf.fit(x_train,y_train)  #Train the Model 

In [ ]:
svr_rbf_confidence = svr_rbf.score(x_test, y_test)
print("svr_rbf accuracy: ", svr_rbf_confidence)

In [ ]:
# Print the predicted value
svm_prediction = svr_rbf.predict(x_test)
print(svm_prediction)

print()

#Print the actual values
print(y_test)

In [ ]:
# Print the model predictions for the next 'n=30' days
svm_prediction = svr_rbf.predict(prediction_days_array)
print(svm_prediction)